Repository sous-chefs/users, pull requests merged in 2021-08, with the labels that each got.

#458 Use the Chef Infra provisioner rather than Zero
  CHANGELOG.md
  kitchen.exec.yml
  kitchen.yml
Labels: Release: Patch

#460 Fix macos && suse gid issue
  CHANGELOG.md
  README.md
  resources/manage.rb
  test/fixtures/cookbooks/users_test/attributes/default.rb
  test/fixtures/data_bags/test_home_dir/databag_username_gid.json
  test/integration/default/default_spec.rb
Labels: Release: Major

#463 Automated PR: Standardising Files
  .github/CODEOWNERS
  CHANGELOG.md
Labels: Release: Patch, Skip: Announcements
