Repository sous-chefs/users, pull requests merged in 2021-03, with the labels that each got.

#444 Add manage_home to remove action of manage resource.
  CHANGELOG.md
  README.md
  resources/manage.rb
Labels: Release: Minor

#445 Make resource independent of data bags
  CHANGELOG.md
  README.md
  libraries/helpers.rb
  metadata.rb
  resources/manage.rb
  spec/manage_spec.rb
  spec/recipes/home_dir_spec.rb
  test/fixtures/cookbooks/users_test/attributes/default.rb
  test/fixtures/cookbooks/users_test/recipes/default.rb
  test/fixtures/data_bags/test_home_dir/bogus_user.json
  test/fixtures/data_bags/test_home_dir/databag_mwaddams.json
  test/fixtures/data_bags/test_home_dir/databag_test_user.json
  test/fixtures/data_bags/test_home_dir/databag_test_user_keys_url.json
  test/fixtures/data_bags/test_home_dir/mwaddams.json
  test/integration/default/default_spec.rb
  upgrading.md
Labels: Release: Major

#449 Fix uid validation multiple places
  CHANGELOG.md
  resources/manage.rb
  test/fixtures/cookbooks/users_test/attributes/default.rb
  test/integration/default/default_spec.rb
Labels: Bug, Release: Patch

#451 Set a default for users property
  CHANGELOG.md
  resources/manage.rb
  test/fixtures/cookbooks/users_test/recipes/default.rb
  test/integration/default/default_spec.rb
Labels: Feature Request, Release: Patch
